version: "3"

services:
  php:
    build: ./php
    depends_on:
      - sql
    env_file:
      - ./docker-compose.env
  app:
    build: ./app
    depends_on:
      - php
    ports:
      - 80:80
  sql:
    build: ./sql
    env_file:
      - ./docker-compose.env